defaults:
  - _self_

# Benchmark settings
benchmark_type: 'control'  # 'control' or 'prediction'
steps_per_game: 10000
use_wandb: false
log_freq: 1000
save_video: false

# List of Atari games to run in sequence
game_order:
  - 'ALE/Pong-v5'
  - 'ALE/Breakout-v5'
  - 'ALE/SpaceInvaders-v5'
  - 'ALE/MsPacman-v5'
  - 'ALE/Asterix-v5'
  - 'ALE/Qbert-v5'
  - 'ALE/Seaquest-v5'
  - 'ALE/BeamRider-v5'
  - 'ALE/Phoenix-v5'
  - 'ALE/Atlantis-v5'
  - 'ALE/Asteroids-v5'
  - 'ALE/BattleZone-v5'
  - 'ALE/Centipede-v5'
  - 'ALE/DemonAttack-v5'
  - 'ALE/Enduro-v5'
  - 'ALE/FishingDerby-v5'
  - 'ALE/IceHockey-v5'
  - 'ALE/Jamesbond-v5'
  - 'ALE/Kangaroo-v5'
  - 'ALE/RoadRunner-v5'

# Wandb settings
wandb:
  project: 'continual_atari'
  entity: null  # Set to your wandb username 