defaults:
  - _self_
  - benchmark


train:
  model_name: 'ppo_atari'
  n_envs: 2
  total_timesteps: 10000000


# Wandb settings
wandb:
  project: 'continual_atari_train_policy'
  entity: null  # Set to your wandb username 